import { Game, Guide } from "./types";

export const GAMES: Game[] = [
  {
    slug: "anno-1800",
    title: "Anno 1800",
    zhTitle: "纪元1800",
    steamAppId: 916440,
    shortDescription: "Master supply chains, optimize production layouts, and build thriving industrial-era cities across multiple islands.",
    zhShortDescription: "掌握供应链，优化生产布局，在群岛之间建造繁荣的工业时代都市。",
    description: "Lead the Industrial Revolution in this award-winning city-building and supply chain management game. Colonize new islands, establish trade routes, and balance the needs of farmers, workers, and investors.",
    zhDescription: "在这款获奖的城市建造与供应链管理游戏中引领工业革命。殖民新岛屿，建立贸易路线，平衡农民、工人和投资人的需求。",
    genres: ["City Builder", "Strategy"],
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/916440/header.jpg",
    headerImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/916440/header.jpg",
    releaseDate: "2019-04-16",
    developer: "Ubisoft Mainz",
    guideCount: 2,
    featured: true,
  },
  {
    slug: "civilization-6",
    title: "Civilization VI",
    zhTitle: "文明VI",
    steamAppId: 289070,
    shortDescription: "Optimize district adjacency, master leader-specific victory paths, and conquer the world one hex at a time.",
    zhShortDescription: "优化区域相邻加成，精通各领袖专属胜利路线，一格一格征服世界。",
    description: "The definitive 4X strategy game. Build an empire to stand the test of time. Explore new lands, research technologies, conduct diplomacy, and lead your civilization from the Stone Age to the Information Age.",
    zhDescription: "终极4X策略游戏。建立一个经得起时间考验的帝国。探索新大陆，研究科技，进行外交，带领你的文明从石器时代走向信息时代。",
    genres: ["4X Strategy", "Turn-Based"],
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg",
    headerImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg",
    releaseDate: "2016-10-21",
    developer: "Firaxis Games",
    guideCount: 2,
    featured: true,
  },
  {
    slug: "rimworld",
    title: "RimWorld",
    zhTitle: "边缘世界",
    steamAppId: 294100,
    shortDescription: "Survive and thrive on the rim — colony management, defense layout, mood optimization, and storyteller-specific strategies.",
    zhShortDescription: "在边缘世界活下去、活得好——殖民管理、防御布局、心情优化、各叙事者专属策略。",
    description: "A sci-fi colony sim driven by an intelligent AI storyteller. Manage colonists' moods, needs, wounds, and illnesses. Build in forests, deserts, tundra, and more. Every game generates a new story.",
    zhDescription: "由智能AI叙事者驱动的科幻殖民模拟游戏。管理殖民者的心情、需求、伤口和疾病。在森林、沙漠、冻土等各种环境中建造。每一局都是全新的故事。",
    genres: ["Colony Sim", "Management"],
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/header.jpg",
    headerImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/header.jpg",
    releaseDate: "2018-10-17",
    developer: "Ludeon Studios",
    guideCount: 2,
    featured: true,
  },
  {
    slug: "farthest-frontier",
    title: "Farthest Frontier",
    zhTitle: "最远的边陲",
    steamAppId: 1044720,
    shortDescription: "Build a medieval town from nothing — farming rotations, resource chains, wall layouts, and disease management.",
    zhShortDescription: "从零建造中世纪城镇——作物轮作、资源链、城墙布局、疾病管理。",
    description: "Protect and guide your people from a handful of settlers to a thriving medieval town. Harvest raw materials, hunt, fish and farm. Craft items, trade, and survive against the elements and outside threats.",
    zhDescription: "保护并引导你的人民从寥寥数人发展成繁荣的中世纪城镇。采集原料、狩猎、捕鱼、耕种。制作物品、贸易，在自然和外部威胁中生存下来。",
    genres: ["City Builder", "Survival"],
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1044720/header.jpg",
    headerImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1044720/header.jpg",
    releaseDate: "2022-08-09",
    developer: "Crate Entertainment",
    guideCount: 2,
    featured: false,
  },
  {
    slug: "going-medieval",
    title: "Going Medieval",
    zhTitle: "前往中世纪",
    steamAppId: 1029780,
    shortDescription: "Design impenetrable castles, manage settler psychology, and survive medieval winters in this 3D colony builder.",
    zhShortDescription: "设计坚不可摧的城堡，管理居民心理，在3D殖民建造中挺过中世纪严冬。",
    description: "Stake your claim in this colony-building sim set in a post-Calamity medieval world. Build multi-story fortresses, manage settlers' moods and needs, and defend against waves of raiders.",
    zhDescription: "在灾变后的中世纪世界中建造殖民地。建造多层堡垒，管理居民心情与需求，抵御一波波掠夺者。",
    genres: ["Colony Sim", "Strategy"],
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1029780/header.jpg",
    headerImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1029780/header.jpg",
    releaseDate: "2021-06-01",
    developer: "Foxy Voxel",
    guideCount: 2,
    featured: false,
  },
  {
    slug: "foundation",
    title: "Foundation",
    zhTitle: "Foundation",
    steamAppId: 690830,
    shortDescription: "Grid-free organic city building — zone industries, manage supply chains, and grow a medieval city that feels alive.",
    zhShortDescription: "无网格有机城市建造——划定工业区、管理供应链、让中世纪城市自然生长。",
    description: "A gridless, organic medieval city-building simulation. Instead of placing individual buildings, paint zones for housing, farming, and industry. Watch your city grow organically as villagers build their own paths and homes.",
    zhDescription: "一款无网格的有机中世纪城市建设模拟游戏。不用逐个放置建筑，只需划定住宅区、农业区和工业区。看着村民自己修路盖房，城市自然生长。",
    genres: ["City Builder", "Management"],
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/690830/header.jpg",
    headerImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/690830/header.jpg",
    releaseDate: "2025-01-31",
    developer: "Polymorph Games",
    guideCount: 2,
    featured: false,
  },
];

export const GUIDES: Guide[] = [
  // Anno 1800
  {
    slug: "production-layouts",
    gameSlug: "anno-1800",
    title: "Anno 1800: The Complete Production Layout Guide",
    zhTitle: "纪元1800：完整生产布局指南",
    description: "Optimize every production chain from farmers to investors. Warehouse placement, road density, and trade union radius explained with exact layouts.",
    zhDescription: "从农民到投资人的每条产业链优化。仓库摆放、道路密度、工会半径，附精确布局图。",
    category: "advanced", difficulty: "medium",
    tags: ["production", "layout", "optimization"],
    wordCount: 5200, estimatedReadTime: 22, publishDate: "2025-11-30",
  },
  {
    slug: "beginner-guide",
    gameSlug: "anno-1800",
    title: "Anno 1800 Beginner Guide: Your First 5 Hours",
    zhTitle: "纪元1800新手攻略：前5个小时",
    description: "From your first warehouse to your first investor. Population tier progression, expedition prep, and the 7 mistakes every new player makes.",
    zhDescription: "从第一个仓库到第一个投资人。人口等级递进、远征准备、以及新手最容易忽视的7个要点。",
    category: "beginner", difficulty: "easy",
    tags: ["beginner", "tutorial", "population"],
    wordCount: 3800, estimatedReadTime: 16, publishDate: "2025-11-12",
  },
  // Civ 6
  {
    slug: "district-guide",
    gameSlug: "civilization-6",
    title: "Civilization VI: District Adjacency Master Guide",
    zhTitle: "文明VI：区域相邻加成完全指南",
    description: "Maximize every district bonus. Campus, Industrial Zone, Theater Square adjacency charts. Wonder placement optimization and the IZ-aqueduct-dam triangle explained.",
    zhDescription: "最大化每个区域的加成。学院区、工业区、剧院广场相邻加成表。奇观摆放优化与工业区-水渠-水坝三角详解。",
    category: "advanced", difficulty: "medium",
    tags: ["districts", "adjacency", "optimization"],
    wordCount: 4500, estimatedReadTime: 19, publishDate: "2025-12-18",
  },
  {
    slug: "victory-paths",
    gameSlug: "civilization-6",
    title: "Civilization VI: Victory Paths for Every Leader",
    zhTitle: "文明VI：全领袖胜利路线",
    description: "Which victory each leader excels at, policy card priorities by era, and the exact tech/civic beeline for Science, Culture, Domination, Religion, and Diplomacy wins.",
    zhDescription: "每个领袖擅长哪种胜利、各时代政策卡优先级、科技/文化/征服/宗教/外交五种胜利的精确科技冲线路线。",
    category: "walkthrough", difficulty: "medium",
    tags: ["victory", "leader", "strategy"],
    wordCount: 6100, estimatedReadTime: 26, publishDate: "2026-01-05",
  },
  // RimWorld
  {
    slug: "defense-layout",
    gameSlug: "rimworld",
    title: "RimWorld: Killbox & Defense Layout Encyclopedia",
    zhTitle: "边缘世界：杀阵与防御布局百科",
    description: "Every killbox design ranked: singularity, heat trap, funnel, and the new meta for each storyteller. Turret placement, cover mechanics, sapper-proofing, and mortar pits.",
    zhDescription: "所有杀阵排名：奇点、热陷阱、漏斗，以及各叙事者的版本答案。炮塔摆放、掩体机制、防工兵策略、迫击炮阵地。",
    category: "advanced", difficulty: "hard",
    tags: ["defense", "killbox", "combat"],
    wordCount: 5600, estimatedReadTime: 24, publishDate: "2026-04-19",
  },
  {
    slug: "mood-management",
    gameSlug: "rimworld",
    title: "RimWorld: Colony Management & Mood Optimization Guide",
    zhTitle: "边缘世界：殖民管理与心情优化指南",
    description: "Complete mood system reference, room impressiveness math, work priority configurations, colony layout templates, and storyteller-specific strategies for a mental-break-free colony.",
    zhDescription: "完整心情系统参考、房间豪华度数学、工作优先级配置、殖民地布局模板，以及零精神崩溃殖民地的叙事者专属策略。",
    category: "walkthrough", difficulty: "medium",
    tags: ["mood", "management", "layout"],
    wordCount: 6200, estimatedReadTime: 26, publishDate: "2026-05-15",
  },
  // Farthest Frontier
  {
    slug: "farming-guide",
    gameSlug: "farthest-frontier",
    title: "Farthest Frontier: Complete Farming & Food Guide",
    zhTitle: "最远的边陲：完整农耕与食物指南",
    description: "Crop rotation for maximum yield, soil fertility management, livestock optimization, and food preservation. Keep your colony fed through the harshest winters.",
    zhDescription: "最大化产量的轮作方案、土壤肥力管理、畜牧业优化、食物保存。让你的殖民地在最严酷的冬天也有饭吃。",
    category: "walkthrough", difficulty: "medium",
    tags: ["farming", "food", "survival"],
    wordCount: 4800, estimatedReadTime: 20, publishDate: "2026-01-22",
  },
  {
    slug: "defense-guide",
    gameSlug: "farthest-frontier",
    title: "Farthest Frontier: Defense, Walls & Town Protection",
    zhTitle: "最远的边陲：防御、城墙与城镇保护",
    description: "Wall engineering from palisade to fortress, tower placement for overlapping coverage, troop composition ratios, disease control protocols, and raider defense strategies.",
    zhDescription: "从木栅栏到要塞的城墙工程、火力重叠的箭塔摆放、部队编制比例、疾病控制方案、掠夺者防御策略。",
    category: "advanced", difficulty: "hard",
    tags: ["defense", "walls", "combat"],
    wordCount: 4600, estimatedReadTime: 19, publishDate: "2026-02-14",
  },
  // Going Medieval
  {
    slug: "castle-defense",
    gameSlug: "going-medieval",
    title: "Going Medieval: Castle Design & Defense Architecture",
    zhTitle: "前往中世纪：城堡设计与防御建筑",
    description: "Layered defense design, wall material engineering, settler mood management, and winter survival. Build a fortress that makes 20-man raids into target practice.",
    zhDescription: "分层防御设计、墙体材料工程、居民心情管理、冬季生存。建造一座让20人袭击变成活靶子练习的要塞。",
    category: "advanced", difficulty: "hard",
    tags: ["defense", "castle", "architecture"],
    wordCount: 5100, estimatedReadTime: 22, publishDate: "2026-03-03",
  },
  {
    slug: "production-chains",
    gameSlug: "going-medieval",
    title: "Going Medieval: Production Chains & Settler Management",
    zhTitle: "前往中世纪：产业链与居民管理",
    description: "Complete production tree from raw resources to steel weapons, settler specialization with star skills, research priority path, and underground storage optimization.",
    zhDescription: "从原材料到钢制武器的完整生产树、天赋技能居民专精、科研优先路径、地下仓储优化。",
    category: "advanced", difficulty: "medium",
    tags: ["production", "crafting", "management"],
    wordCount: 4300, estimatedReadTime: 18, publishDate: "2026-03-28",
  },
  // Foundation
  {
    slug: "city-layout",
    gameSlug: "foundation",
    title: "Foundation: Organic City Layout & Supply Chain Guide",
    zhTitle: "Foundation：有机城市布局与供应链指南",
    description: "Zone planning for organic growth, complete supply chain reference, monument building workflow, and trade economy mastery for a thriving medieval city.",
    zhDescription: "有机生长的区域规划、完整供应链参考、纪念碑建造流程、贸易经济精通——打造繁荣的中世纪城市。",
    category: "beginner", difficulty: "easy",
    tags: ["layout", "supply-chain", "trade"],
    wordCount: 4200, estimatedReadTime: 18, publishDate: "2025-10-15",
  },
  {
    slug: "economy-mastery",
    gameSlug: "foundation",
    title: "Foundation: Economy Mastery & Trade Domination",
    zhTitle: "Foundation：经济大师与贸易制霸",
    description: "Villager promotion pipeline (60-25-15 rule), trade route mastery optimization, monument ROI analysis, and gold management strategies for a self-sustaining medieval economy.",
    zhDescription: "居民晋升路径（60-25-15法则）、贸易路线精通优化、纪念碑投资回报分析、自给自足的中世纪经济策略。",
    category: "advanced", difficulty: "medium",
    tags: ["economy", "trade", "gold"],
    wordCount: 4500, estimatedReadTime: 19, publishDate: "2025-10-28",
  },
];
