/**
 * Game database access layer.
 * Reads from JSON files generated by scripts/fetch-steam.ts.
 *
 * Uses Next.js JSON imports (resolveJsonModule: true in tsconfig).
 * Fallback empty stubs are in src/data/ to prevent build errors before the pipeline runs.
 */

import type { GameEntry, GamesLikeEntry, BestGamesCategory, TagEntry } from "@/lib/types";

// Static JSON imports — fallback files exist so the build never crashes
import gamesIndex from "@/data/games/index.json";

// -- Games --

const GAMES: GameEntry[] = (gamesIndex as { games?: GameEntry[] }).games ?? [];

export function getAllGames(): GameEntry[] {
  return GAMES;
}

export function getGameBySlug(slug: string): GameEntry | null {
  return GAMES.find((g) => g.slug === slug) ?? null;
}

export function getGamesByTag(tagSlug: string): GameEntry[] {
  return GAMES.filter((g) => g.tags.includes(tagSlug));
}

export function getGamesByTags(tagSlugs: string[]): GameEntry[] {
  return GAMES.filter((g) => tagSlugs.every((t) => g.tags.includes(t)));
}

export function getFeaturedGames(count = 6): GameEntry[] {
  return GAMES.filter((g) => g.featured).slice(0, count);
}

// -- Games Like --

import gamesLikeIndex from "@/data/games-like/index.json";

const GAMES_LIKE: Record<string, GamesLikeEntry> = gamesLikeIndex as Record<string, GamesLikeEntry>;

export function getGamesLike(slug: string): GamesLikeEntry | null {
  return GAMES_LIKE[slug] ?? null;
}

// -- Best Games --

import bestGamesIndex from "@/data/best-games/index.json";

const BEST_GAMES: Record<string, BestGamesCategory> = bestGamesIndex as Record<string, BestGamesCategory>;

export function getBestCategory(slug: string): BestGamesCategory | null {
  return BEST_GAMES[slug] ?? null;
}

export function getAllBestCategories(): BestGamesCategory[] {
  return Object.values(BEST_GAMES);
}

// -- Tags --

import tagsIndex from "@/data/tags/index.json";

const TAGS: Record<string, TagEntry> = tagsIndex as Record<string, TagEntry>;

export function getTag(slug: string): TagEntry | null {
  return TAGS[slug] ?? null;
}

export function getAllTags(): TagEntry[] {
  return Object.values(TAGS);
}
