// Game terminology dictionary — used by GuideTrans for inline term translation.
// Format: English term → "English (中文)" or just "中文" for pure translations.
// Numbers stay as Arabic numerals. Game-specific proper nouns get (中文) annotation.

export const GAME_TERMS: Record<string, string> = {
  // ─── Anno 1800 ───
  Farmers: "农民",
  Workers: "工人",
  Artisans: "工匠",
  Engineers: "工程师",
  Investors: "投资人",
  "Old World": "旧世界",
  "New World": "新世界",
  Arctic: "北极",
  Enbesa: "安贝沙",
  "Crown Falls": "皇冠瀑布",
  Manola: "马诺拉",
  "production chain": "产业链",
  "production chains": "产业链",
  "Trade Union": "工会",
  warehouse: "仓库",
  fishery: "渔场",
  "framework knitters": "织布工坊",
  "potato farm": "土豆农场",
  "schnapps distillery": "烈酒蒸馏厂",
  "pig farm": "养猪场",
  "rendering works": "油脂提炼厂",
  bakery: "面包房",
  brewery: "啤酒厂",
  cannery: "罐头厂",
  "fur dealer": "皮草商",
  "sewing machine factory": "缝纫机工厂",
  "cotton plantation": "棉花种植园",
  "cotton mill": "轧棉厂",
  "sugar cane": "甘蔗",
  "rum distillery": "朗姆酒蒸馏厂",
  "coffee plantation": "咖啡种植园",
  "coffee roaster": "咖啡烘焙厂",
  "gold mine": "金矿",
  "gold ore": "金矿石",
  "iron mine": "铁矿",
  "copper mine": "铜矿",
  "zinc mine": "锌矿",
  "sand mine": "砂矿",
  "brass smelter": "黄铜冶炼厂",
  "glassmakers": "玻璃作坊",
  "spectacle factory": "眼镜工厂",
  "light bulb factory": "灯泡工厂",
  "pocket watch": "怀表",
  "steam carriage": "蒸汽马车",
  "steam motor": "蒸汽发动机",
  champagne: "香槟",
  cigars: "雪茄",
  chocolate: "巧克力",
  "oil power plant": "燃油发电站",
  "gas power plant": "燃气发电站",
  electricity: "电力",
  clipper: "快船",
  airship: "飞艇",
  expedition: "远征",
  "Trade Union item": "工会物品",
  "Ctrl+Q": "Ctrl+Q",
  "production stats": "生产统计",
  "production screen": "生产面板",
  "Grand Gallery": "大画廊",
  "Loading Ramp": "装卸台",
  carts: "运输车",
  "17 tiles": "17 格",
  "17-tile": "17 格",
  "road distance": "道路距离",
  "paved roads": "石板路",
  "Dario the Mechanical Engineer": "机械工程师达里奥",
  "Eli Bleakworth": "伊莱·布利克沃斯",
  "Isabel Sarmento": "伊莎贝尔·萨门托",
  "stone roads": "石板路",
  plank: "木板",
  timber: "原木",
  "steel beam": "钢梁",
  brick: "砖",

  // ─── Civilization VI ───
  Campus: "学院区",
  "Industrial Zone": "工业区",
  "Theater Square": "剧院广场",
  "Holy Site": "圣地",
  "Commercial Hub": "商业中心",
  Harbor: "港口",
  Encampment: "军营",
  "Government Plaza": "政府广场",
  "Diplomatic Quarter": "外交区",
  Preserve: "保护区",
  "Entertainment Complex": "娱乐中心",
  "Water Park": "水上乐园",
  Aqueduct: "水渠",
  Dam: "水坝",
  Canal: "运河",
  adjacency: "相邻加成",
  "major adjacency": "主要加成",
  "minor adjacency": "次要加成",
  "Natural Philosophy": "自然哲学",
  Craftsmen: "工匠",
  "Five-Year Plan": "五年计划",
  Aesthetics: "美学",
  Scripture: "经文",
  "Town Charters": "城镇特许状",
  "Coal Power Plant": "燃煤发电厂",
  Factory: "工厂",
  "Ruhr Valley": "鲁尔山谷",
  "Oxford University": "牛津大学",
  Petra: "佩特拉古城",
  "Mausoleum at Halicarnassus": "摩索拉斯王陵墓",
  Colosseum: "罗马斗兽场",
  "Kilwa Kisiwani": "基卢瓦基西瓦尼",
  Germany: "德国",
  Japan: "日本",
  Korea: "韩国",
  Russia: "俄罗斯",
  Greece: "希腊",
  Mali: "马里",
  Hansa: "汉萨商会",
  Seowon: "书院",
  Lavra: "修道院",
  Acropolis: "卫城",
  Suguba: "苏古巴",
  "Meiji Restoration": "明治维新",
  "Science Victory": "科技胜利",
  "Culture Victory": "文化胜利",
  "Domination Victory": "征服胜利",
  "Religious Victory": "宗教胜利",
  "Diplomatic Victory": "外交胜利",
  Mountains: "山脉",
  Reefs: "珊瑚礁",
  "Geothermal Fissure": "地热裂缝",
  Rainforest: "雨林",
  districts: "区域",
  "policy card": "政策卡",
  "Great Scientist": "大科学家",
  "Great Engineer": "大工程师",
  "Great General": "大将军",
  "Spaceport": "宇航中心",
  "Terrestrial Laser Station": "地面激光站",
  bombards: "攻城单位",
  "Battering Ram": "攻城槌",
  "Swordsman": "剑士",
  Knight: "骑士",
  Frigate: "护卫舰",
  "Privateer": "私掠船",
  Bomber: "轰炸机",
  Tank: "坦克",
  tourism: "旅游业绩",
  "Rock Bands": "摇滚乐队",
  "National Parks": "国家公园",
  "Seaside Resorts": "海滨度假区",

  // ─── RimWorld ───
  killbox: "杀阵",
  killboxes: "杀阵",
  "mental break": "精神崩溃",
  "mood cascade": "心情连锁崩溃",
  storyteller: "叙事者",
  "Cassandra Classic": "卡桑德拉经典",
  "Phoebe Chillax": "菲比休闲",
  "Randy Random": "兰迪随机",
  sapper: "工兵",
  centipede: "机械蜈蚣",
  "colonist mood": "殖民者心情",
  "Mental Break": "精神崩溃",
  "Extreme Break": "极度崩溃",
  "bedroom impressiveness": "卧室豪华度",
  "dining room": "餐厅",
  "recreation room": "娱乐室",
  "fine meal": "精致餐点",
  "lavish meal": "奢侈餐点",
  "beer (drug)": "啤酒",
  "psychite tea": "精神茶",
  "smokeleaf": "烟叶",
  yayo: "雅瑶",
  "emp grenade": "EMP 手雷",
  "heater in": "取暖器",
  "Hospital bed": "医疗床",
  "vitals monitor": "生命监测仪",
  "Hospital + Medicine": "医务室 + 药品库",
  Freezer: "冷冻库",
  Kitchen: "厨房",
  "Tool Cabinet": "工具柜",
  "Butcher Table": "屠宰桌",
  "Sterile Tile": "无菌地板",
  "Marble Wall": "大理石墙",
  "Sculptures in workspaces": "工作区的雕塑",
  "Sculptures in workspaces.": "工作区摆放雕塑。",
  "4+ recreation types available": "4 种以上的娱乐类型可用",
  "beauty per tile": "每格美观度",
  armchair: "扶手椅",
  "cloth armchair": "布艺扶手椅",
  "synthread armchair": "合成纤维扶手椅",
  comfort: "舒适度",
  sarcophagus: "石棺",
  "colonist died": "殖民者死亡",
  "organ harvesting": "器官摘取",
  "butchering humanlike": "屠宰类人生物",
  "Disturbed sleep": "睡眠被打扰",
  "Ate without table": "没桌子吃饭",
  "Slept on ground": "睡在地上",
  Observed: "目睹",
  "rotting corpse": "腐烂尸体",
  "In pain": "疼痛",

  // ─── Farthest Frontier ───
  palisade: "木栅栏",
  compost: "堆肥",
  "root cellar": "根窖",
  granary: "粮仓",
  smokehouse: "熏制房",
  "sauerkraut maker": "酸菜缸",
  cheesemaker: "奶酪作坊",
  "rat catcher": "捕鼠人",
  latrine: "厕所",
  dysentery: "痢疾",
  plague: "瘟疫",
  scurvy: "坏血病",
  tetanus: "破伤风",
  "battering ram": "攻城槌",
  watchtower: "瞭望塔",
  "stone tower": "石塔",
  "fortified tower": "加固塔",
  "fortified stone wall": "加固石墙",
  crossbowman: "弩手",
  spearman: "矛兵",

  // ─── Going Medieval ───
  "Z-level": "层 (Z轴)",
  battlements: "城垛",
  merlons: "垛口",
  gatehouse: "门楼",
  "murder hole": "杀人孔",
  "killing field": "杀戮区",
  limestone: "石灰岩",
  granite: "花岗岩",
  "clay brick": "黏土砖",
  trebuchet: "投石机",
  brazier: "火盆",
  "linen clothing": "亚麻衣服",
  "leather armor": "皮甲",
  "iron armor": "铁甲",
  "steel weapon": "钢制武器",
  "smoked meat": "熏肉",
  "preserved food": "腌制食物",
  "★ (star skill)": "★（天赋技能）",
  "star skill": "天赋技能",
  carpenter: "木匠",
  stonemason: "石匠",
  blacksmith: "铁匠",
  tailor: "裁缝",
  weaver: "织工",
  tanner: "制皮匠",
  armorer: "盔甲匠",
  weaponsmith: "武器匠",
  fletcher: "箭匠",
  brewer: "酿酒师",

  // ─── Foundation ───
  Serf: "农奴",
  Commoner: "平民",
  Citizen: "市民",
  "Village Church": "乡村教堂",
  "Lord's Manor": "领主庄园",
  "Grand Fountain": "大喷泉",
  Cathedral: "大教堂",
  "Monastery": "修道院",
  "Tax Office": "税务局",
  Jeweler: "珠宝匠",
  "Stained Glass": "彩色玻璃",
  "Trade Route": "贸易路线",
  "Trade Mastery": "贸易精通",
  Northburgh: "北堡",
  Kallio: "卡利奥",
  "bread (trade good)": "面包",
  "Iron Tools": "铁制工具",
  Jewelry: "珠宝",
  "Gold Mine": "金矿",
  "Sand Pit": "采砂场",
  "Quartz Mine": "石英矿",
  "Iron Bars": "铁锭",
  "Steel Ingots": "钢锭",
  "Wheat Farm": "小麦农场",
  Windmill: "风车",
  Brewery: "啤酒厂",
  "Hop Farm": "啤酒花农场",
  "Sheep Farm": "牧羊场",
  "Coal Mine": "煤矿",
  "desirability": "吸引力",

  // ─── Common terms ───
  "DLC Bosses": "DLC Boss",
  population: "人口",
  maintenance: "维护费",
  productivity: "生产力",
  efficiency: "效率",
  "optimal ratio": "最优比例",
  "Pop Supported": "支持人口",
  "attack pattern": "攻击模式",
  "healing window": "治疗窗口",
  "charm loadout": "护符搭配",
  staggering: "失衡",
  stagger: "失衡",
  "death defiance": "死里逃生",
  "hp (health)": "HP（生命值）",
  dps: "DPS",
  "dps (damage per second)": "DPS（每秒伤害）",
  aoe: "AoE",
  "AoE (area of effect)": "AoE（范围效果）",
  dot: "DoT",
  "DoT (damage over time)": "DoT（持续伤害）",
  "i-frames": "无敌帧",
  "the meta": "版本答案",
  micro: "微操",
  "number of buildings": "建筑数量",
  "One clipper dedicated route": "一艘快船专门跑这条航线",
  "One clipper set to": "一艘快船设置为",
  "full — gold is dense": "满载——黄金很重",
  "output": "产出",
  "food supply": "食物供给",
  "gold income": "金币收入",
  "monthly return": "月回报",
  "raid size": "袭击规模",
  settlement: "定居点",
  blight: "枯萎病",
  frost: "霜冻",
  medicine: "药品",
  bandage: "绷带",
  quarantine: "隔离",
  infection: "感染",
};

/** Translate inline game-term usage: e.g., "Quick Slash" → "Quick Slash (快速斩击)" */
export function translateTerm(en: string, toZh: boolean): string {
  if (!toZh) return en;
  return GAME_TERMS[en] || en;
}
