import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getBestCategory, getAllBestCategories, getGameBySlug } from "@/lib/game-data";
import type { Lang } from "@/lib/i18n";
import { BestGamesList } from "@/components/discovery/best-games-list";
import { LocalLink as Link } from "@/components/layout/local-link";

interface Props {
  params: Promise<{ lang: string; slug: string }>;
}

export async function generateStaticParams() {
  const categories = getAllBestCategories();
  return categories.flatMap((cat) => [
    { lang: "en", slug: cat.slug },
    { lang: "zh", slug: cat.slug },
  ]);
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang, slug } = await params;
  const cat = getBestCategory(slug);
  if (!cat) return { title: "Not Found" };

  const title = lang === "zh" ? cat.titleZh : cat.titleEn;
  const desc = lang === "zh" ? cat.descriptionZh : cat.descriptionEn;

  return {
    title,
    description: desc,
    openGraph: { title, description: desc },
  };
}

export default async function BestGamesPage({ params }: Props) {
  const { lang, slug } = await params;
  const cat = getBestCategory(slug);
  if (!cat) notFound();

  const langKey: Lang = lang === "zh" ? "zh" : "en";

  const rankedGames = cat.games
    .map((entry) => {
      const game = getGameBySlug(entry.slug);
      return game ? { game, rank: entry.rank, reasonEn: entry.reasonEn, reasonZh: entry.reasonZh } : null;
    })
    .filter((r): r is NonNullable<typeof r> => r !== null)
    .sort((a, b) => a.rank - b.rank);

  return (
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-20">
      <section className="mb-12">
        <nav className="mb-4 flex items-center gap-2 text-xs text-[var(--muted)]">
          <Link href="/" className="hover:text-[var(--neon)] transition-colors">Home</Link>
          <span>/</span>
          <Link href="/games" className="hover:text-[var(--neon)] transition-colors">
            {langKey === "zh" ? "游戏库" : "Games"}
          </Link>
          <span>/</span>
          <span className="text-[var(--fg)]/80">
            {langKey === "zh" ? cat.titleZh : cat.titleEn}
          </span>
        </nav>

        <h1 className="mt-4 font-display text-3xl font-bold tracking-tight sm:text-4xl">
          {langKey === "zh" ? cat.titleZh : cat.titleEn}
        </h1>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-[var(--muted)]">
          {langKey === "zh" ? cat.descriptionZh : cat.descriptionEn}
        </p>
      </section>

      <BestGamesList games={rankedGames} lang={langKey} />

      <p className="mt-8 text-center text-[10px] text-[var(--muted)]/50">
        {langKey === "zh"
          ? "榜单由 Vault AI 根据玩法质量、社区评分和玩家口碑综合生成"
          : "Rankings generated by Vault AI based on gameplay quality, community ratings, and player reception"}
      </p>
    </div>
  );
}
