import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getAllGames, getGameBySlug, getGamesLike } from "@/lib/game-data";
import { getSimilarGames } from "@/lib/similarity";
import type { Lang } from "@/lib/i18n";
import { GamesLikeGrid } from "@/components/discovery/games-like-grid";
import { LocalLink as Link } from "@/components/layout/local-link";

interface Props {
  params: Promise<{ lang: string; slug: string }>;
}

export async function generateStaticParams() {
  const games = getAllGames();
  return games.flatMap((g) => [
    { lang: "en", slug: g.slug },
    { lang: "zh", slug: g.slug },
  ]);
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang, slug } = await params;
  const game = getGameBySlug(slug);
  const title = (lang === "zh" ? game?.zhTitle : game?.title) || slug;

  return {
    title: `Games Like ${title} — Similar Games You'll Love`,
    description: `Discover games similar to ${title}. Hand-picked recommendations based on gameplay, genre, and player community.`,
  };
}

export default async function GamesLikePage({ params }: Props) {
  const { lang, slug } = await params;
  const game = getGameBySlug(slug);
  if (!game) notFound();

  const allGames = getAllGames();

  const langKey: Lang = lang === "zh" ? "zh" : "en";
  const title = langKey === "zh"
    ? (game.zhTitle || game.title)
    : game.title;

  // Priority: curated data → dynamic engine
  const gamesLikeData = getGamesLike(slug);
  const dynamicRecs = getSimilarGames(game, allGames, 6);

  const recommendations = (gamesLikeData?.recommendations ?? dynamicRecs)
    .map((r) => {
      const recGame = getGameBySlug(r.slug);
      return recGame ? { game: recGame, slug: r.slug, similarityScore: r.similarityScore, reasonEn: r.reasonEn, reasonZh: r.reasonZh } : null;
    })
    .filter((r): r is NonNullable<typeof r> => r !== null);

  return (
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-20">
      {/* Header */}
      <section className="mb-12">
        <nav className="mb-4 flex items-center gap-2 text-xs text-[var(--muted)]">
          <Link href="/" className="hover:text-[var(--neon)] transition-colors">Home</Link>
          <span>/</span>
          <Link href="/games" className="hover:text-[var(--neon)] transition-colors">
            {langKey === "zh" ? "游戏库" : "Games"}
          </Link>
          <span>/</span>
          <span className="text-[var(--fg)]/80">
            {langKey === "zh" ? `类似 ${title} 的游戏` : `Games Like ${title}`}
          </span>
        </nav>

        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="max-w-2xl">
            <h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">
              {langKey === "zh"
                ? `类似 ${title} 的游戏`
                : `Games Like ${title}`}
            </h1>
            <p className="mt-3 text-sm leading-relaxed text-[var(--muted)]">
              {gamesLikeData
                ? (langKey === "zh" ? gamesLikeData.introZh : gamesLikeData.introEn)
                : (langKey === "zh"
                  ? `如果你喜欢 ${title}，这些游戏可能会适合你。基于玩法、类型和玩家社区推荐的类似游戏。`
                  : `If you enjoy ${title}, you'll likely enjoy these games too. Recommendations based on gameplay, genre, and community overlap.`)}
            </p>
          </div>
          {game?.coverImage && (
            <img
              src={game.coverImage}
              alt={title}
              className="h-24 w-auto rounded-lg border border-[var(--border)] object-cover sm:h-32"
            />
          )}
        </div>
      </section>

      {/* Recommendations */}
      {recommendations.length > 0 ? (
        <GamesLikeGrid recommendations={recommendations} lang={langKey} sourceGame={title} />
      ) : (
        <div className="rounded-xl border border-dashed border-[var(--border)] bg-[var(--card)]/30 p-12 text-center">
          <p className="text-sm text-[var(--muted)]">
            {langKey === "zh"
              ? "推荐数据正在生成中，稍后回来查看。"
              : "Recommendations are being generated. Check back soon."}
          </p>
        </div>
      )}

      {/* AI label */}
      {recommendations.length > 0 && (
        <p className="mt-8 text-center text-[10px] text-[var(--muted)]/50">
          {langKey === "zh"
            ? "推荐由 Vault AI 根据游戏机制、标签和玩家重叠度生成"
            : "Recommendations generated by Vault AI based on gameplay mechanics, tags, and player overlap"}
        </p>
      )}
    </div>
  );
}
